import type { Provider } from "../../../types/api";

interface AccordionOptions {
	/**
	 * <summary>タグ内に表示するタイトル
	 * デフォルトは「💡 詳細を表示」
	 */
	title?: string;
	/**
	 * プロバイダー情報を含める場合は指定
	 */
	provider?: Provider;
}

/**
 * コンテンツをアコーディオン(折りたたみ)形式でフォーマットする
 *
 * @example
 * ```ts
 * const content = "レビュー内容...";
 * const formatted = formatAsAccordion(content, {
 *   title: "レビューを表示",
 *   provider: "openai",
 * });
 * ```
 */
export function formatAsAccordion(
	content: string,
	options: AccordionOptions = {},
): string {
	const { title = "💡 詳細を表示", provider } = options;

	return `<details>
<summary>
<h4>${title}</h4>
</summary>

${content}
</details>

${provider ? `(generated by ${provider})` : ""}`;
}
