import { describe, expect, test } from "vitest";
import { formatAsAccordion } from "../../../../src/app/utils/github/comments";

describe("formatAsAccordion", () => {
	test("デフォルトオプションでコンテンツを折りたたみ形式にフォーマットする", () => {
		const content = "テストコンテンツ";
		const formatted = formatAsAccordion(content);

		expect(formatted).toBe(`<details>
<summary>
<h4>💡 詳細を表示</h4>
</summary>

テストコンテンツ
</details>

`);
	});

	test("カスタムタイトルを指定して折りたたみを作成する", () => {
		const content = "テストコンテンツ";
		const formatted = formatAsAccordion(content, {
			title: "カスタムタイトル",
		});

		expect(formatted).toBe(`<details>
<summary>
<h4>カスタムタイトル</h4>
</summary>

テストコンテンツ
</details>

`);
	});

	test("プロバイダー情報付きで折りたたみを作成する", () => {
		const content = "テストコンテンツ";
		const formatted = formatAsAccordion(content, {
			provider: "openai",
		});

		expect(formatted).toBe(`<details>
<summary>
<h4>💡 詳細を表示</h4>
</summary>

テストコンテンツ
</details>

(generated by openai)`);
	});

	test("プロバイダーの絵文字をカスタマイズして折りたたみを作成する", () => {
		const content = "テストコンテンツ";
		const formatted = formatAsAccordion(content, {
			provider: "openai",
		});

		expect(formatted).toBe(`<details>
<summary>
<h4>💡 詳細を表示</h4>
</summary>

テストコンテンツ
</details>

(generated by openai)`);
	});

	test("複数行のコンテンツを正しく折りたたみ形式にする", () => {
		const content = `1行目
2行目
3行目`;
		const formatted = formatAsAccordion(content);

		expect(formatted).toBe(`<details>
<summary>
<h4>💡 詳細を表示</h4>
</summary>

1行目
2行目
3行目
</details>

`);
	});

	test("すべてのオプションを指定して折りたたみを作成する", () => {
		const content = "テストコンテンツ";
		const formatted = formatAsAccordion(content, {
			title: "カスタムタイトル",
			provider: "gemini",
		});

		expect(formatted).toBe(`<details>
<summary>
<h4>カスタムタイトル</h4>
</summary>

テストコンテンツ
</details>

(generated by gemini)`);
	});

	test("Markdown形式のコンテンツを保持して折りたたみを作成する", () => {
		const content = `# 見出し

- リスト項目1
- リスト項目2

\`\`\`typescript
const code = "サンプル";
\`\`\``;
		const formatted = formatAsAccordion(content);

		expect(formatted).toBe(`<details>
<summary>
<h4>💡 詳細を表示</h4>
</summary>

# 見出し

- リスト項目1
- リスト項目2

\`\`\`typescript
const code = "サンプル";
\`\`\`
</details>

`);
	});
});
