name: Deploy Firebase Functions

on:
  push:
    branches:
      - release/github-actions

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          cd functions
          touch .env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env
      - name: Install dependencies
        run: npm install
        working-directory: ./functions
      - name: Deploy Firebase Functions
        run: |
          cd functions
          npm install -g firebase-tools
          firebase deploy --only functions --project ${{ secrets.GCLOUD_PROJECT_ID }}